# render.yaml (放在專案根目錄)
services:
  - type: web
    name: liff-wardrobe-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
